import { useMemo, useState } from "react"
import Head from "next/head"
import CategoriesSidePanel from "../components/categorySidepanel"
import Category from "../components/category"
import axios from "axios"
import { myError } from "../lib/error"

export default function Categories() {
  const [open, setOpen] = useState(false)

  const [templates, setTemplates] = useState([])

  useMemo(() => {
    const data = async () => {
      try {
        const getAllTemplates = await axios.get(
          "https://query-management-system.vercel.app/category/get"
        )
        setTemplates(getAllTemplates.data)
      } catch (error) {
        myError({ error })
      }
    }
    data()
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CategoriesSidePanel open={open} setOpen={setOpen} setTemplates={setTemplates} />

        <header className="bg-white shadow">
          <div className="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8 flex flex-wrap items-center justify-between">
            <h1 className="text-3xl font-bold tracking-tight text-gray-900">Templates</h1>
            <div className="items-center justify-end md:flex md:flex-1 lg:w-0">
              <button
                onClick={() => setOpen(true)}
                className="inline-flex items-center justify-center whitespace-nowrap rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-base font-medium text-white shadow-sm hover:bg-indigo-700"
              >
                Add New Category
              </button>
            </div>
          </div>
        </header>

        <main>
          <div className="bg-gray-50">
            <div className="mx-auto max-w-7xl py-6">
              <Category templates={templates} />
            </div>
          </div>
        </main>
      </main>
    </>
  )
}
