import Head from "next/head"
import { Fragment, useState, useMemo, useEffect } from "react"
import { Dialog, Transition } from "@headlessui/react"
import { XMarkIcon } from "@heroicons/react/24/outline"
import { FunnelIcon } from "@heroicons/react/20/solid"
import { useRouter } from "next/router"
import { myError } from "../lib/error"

export default function Category() {
  const router = useRouter()
  const [templates, setTemplates] = useState([])

  useEffect(() => {
    const data = async () => {
      try {
        const getAllTemplates = await fetch(
          "https://query-management-system.vercel.app/category/get",
          {
            method: "GET",
          }
        )
        const AllTemplates = await getAllTemplates.json()
        setTemplates(AllTemplates)
      } catch (error) {
        myError({ error })
      }
    }
    data()
  }, [])

  function handleOpen({ id }: any) {
    router.push(`/templates/${id}`)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white">
        <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="flex items-baseline justify-between border-b border-gray-200 pt-12 pb-6">
            <h1 className="text-4xl font-bold tracking-tight text-gray-900">Categories</h1>
          </div>

          <section aria-labelledby="products-heading" className="pt-8 pb-24 mx-5">
            <h2 id="products-heading" className="sr-only">
              Products
            </h2>

            <div className="mt-6 space-y-12 lg:grid lg:grid-cols-2 lg:gap-x-6 lg:space-y-0">
              {templates.map((template: any) => {
                return (
                  <div
                    key={template._id}
                    className="group relative mb-7"
                    onClick={() => handleOpen({ id: template.category })}
                  >
                    <div className="relative h-80 w-full mb-5 overflow-hidden shadow-lg rounded bg-white group-hover:opacity-75 sm:aspect-w-2 sm:aspect-h-1 sm:h-64 lg:aspect-w-1 lg:aspect-h-1">
                      <img
                        src={template.imageSrc}
                        alt={template.imageAlt}
                        className="h-full w-full object-cover object-center"
                      />
                    </div>
                    <h3 className="text-base font-semibold text-gray-900">{template.name}</h3>
                  </div>
                )
              })}
            </div>
          </section>
        </main>
      </main>
    </>
  )
}
